#!/bin/bash
set -e

# Cortex Agent Chat - Setup Automation
# Generates RSA key-pair and creates demo user for Snowsight deployment
# Author: SE Community

# Demo user configuration (no user input required)
DEMO_USER="SFE_CORTEX_DEMO_USER"
DEMO_ROLE="SFE_CORTEX_DEMO_ROLE"
DEMO_WAREHOUSE="SFE_CORTEX_AGENT_WH"

echo "=========================================="
echo "Cortex Agent Chat - Setup Automation"
echo "=========================================="
echo ""
echo "This script will:"
echo "  1. Generate RSA key-pair for authentication"
echo "  2. Create SQL to set up demo user: $DEMO_USER"
echo "  3. Configure .env.server.local for the backend proxy (private key stays server-side)"
echo ""

# Check for required tools
if ! command -v openssl &> /dev/null; then
    echo "❌ Error: openssl not found. Please install OpenSSL first."
    exit 1
fi

echo "Generating RSA key-pair..."

# Generate private key (2048-bit RSA in PKCS#8 format)
# PKCS#8 is required by Snow CLI and works with backend JWT generation
openssl genpkey -algorithm RSA -out rsa_key.pem -pkeyopt rsa_keygen_bits:2048 2>/dev/null

# Extract public key
openssl rsa -in rsa_key.pem -pubout -out rsa_key.pub 2>/dev/null

# Extract public key content (without BEGIN/END lines)
PUBLIC_KEY=$(grep -v "BEGIN PUBLIC KEY" rsa_key.pub | grep -v "END PUBLIC KEY" | tr -d '\n')

# Get private key content for .env.local (with newlines as literal \n)
# This creates a single-line string with \n escape sequences
PRIVATE_KEY_ESCAPED=$(awk 'NR>1{printf "\\n"}{printf "%s",$0}' rsa_key.pem)

echo "✅ RSA key-pair generated successfully!"
echo "   - Private key: rsa_key.pem"
echo "   - Public key: rsa_key.pub"
echo ""

# Create backend env (server-side only, holds the private key)
cat > .env.server.local << EOF
# Cortex Agent Chat - Backend Configuration
# Generated: $(date +%Y-%m-%d)
# WARNING: Never commit this file! Contains private key.

# Snowflake Connection (server-side)
SNOWFLAKE_ACCOUNT=your-account.us-east-1
SNOWFLAKE_USER=$DEMO_USER
SNOWFLAKE_DATABASE=SNOWFLAKE_EXAMPLE
SNOWFLAKE_SCHEMA=SFE_CORTEX_AGENT_CHAT
SNOWFLAKE_AGENT_NAME=SFE_REACT_DEMO_AGENT

# RSA Private Key (generated: $(date +%Y-%m-%d))
SNOWFLAKE_PRIVATE_KEY_PEM="$PRIVATE_KEY_ESCAPED"

# Backend port
PORT=4000
EOF

echo "✅ Created .env.server.local (backend) configuration file"
echo ""

# Verify the private key was written correctly
if grep -q "BEGIN PRIVATE KEY" .env.server.local && grep -q "END PRIVATE KEY" .env.server.local; then
    echo "✅ Private key format verified in .env.server.local"
else
    echo "⚠️  WARNING: Private key format issue detected!"
    echo "   Manually copy rsa_key.pem content to .env.server.local"
fi
echo ""

# Create frontend env (no secrets)
cat > .env.local << EOF
# Cortex Agent Chat - Frontend Configuration (no secrets)
# Generated: $(date +%Y-%m-%d)

# Snowflake Connection (non-secret)
REACT_APP_SNOWFLAKE_ACCOUNT=your-account.us-east-1
REACT_APP_SNOWFLAKE_USER=$DEMO_USER

# Agent Configuration
REACT_APP_SNOWFLAKE_DATABASE=SNOWFLAKE_EXAMPLE
REACT_APP_SNOWFLAKE_SCHEMA=SFE_CORTEX_AGENT_CHAT
REACT_APP_CORTEX_AGENT_NAME=SFE_REACT_DEMO_AGENT
EOF

echo "✅ Created .env.local (frontend) configuration file"
echo ""

# Generate complete SQL script
SQL_OUTPUT="deploy_with_key.sql"

cat > "$SQL_OUTPUT" << 'EOFHEADER'
-- Cortex Agent Chat - Complete Setup
-- Generated by tools/01_setup.sh
-- Creates demo user + deploys agent + assigns public key
-- 
-- INSTRUCTIONS:
-- 1. Copy this ENTIRE script
-- 2. Paste into Snowsight (as ACCOUNTADMIN or role with CREATE USER privilege)
-- 3. Click "Run All"
-- 4. Return to terminal and run: npm install && npm start

-- ============================================
-- STEP 1: Create Demo User and Role
-- ============================================
-- This creates a dedicated demo user for key-pair authentication

EOFHEADER

# Add user/role creation SQL (BEFORE deploy.sql)
cat >> "$SQL_OUTPUT" << EOF
USE ROLE ACCOUNTADMIN;

-- Create warehouse for this tool
CREATE WAREHOUSE IF NOT EXISTS $DEMO_WAREHOUSE
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'DEMO: Warehouse for Cortex Agent Chat demo';

-- Create demo role if not exists
CREATE ROLE IF NOT EXISTS $DEMO_ROLE
    COMMENT = 'DEMO: Role for Cortex Agent Chat demo user';

-- Create demo user with key-pair authentication ONLY (no password)
CREATE USER IF NOT EXISTS $DEMO_USER
    DEFAULT_ROLE = $DEMO_ROLE
    DEFAULT_WAREHOUSE = $DEMO_WAREHOUSE
    TYPE = SERVICE
    COMMENT = 'DEMO: Demo user for Cortex Agent Chat (key-pair auth only)';

-- Assign role to user
GRANT ROLE $DEMO_ROLE TO USER $DEMO_USER;

-- ============================================
-- STEP 2: Deploy Cortex Agent
-- ============================================
-- This creates the schema, agent, and warehouse
-- Grants come AFTER these objects exist

EOF

# Append the original deploy.sql content
cat deploy.sql >> "$SQL_OUTPUT"

# Add grants and public key assignment AFTER objects exist
cat >> "$SQL_OUTPUT" << EOF

-- ============================================
-- STEP 3: Grant Permissions to Demo Role
-- ============================================
-- These grants come AFTER deploy.sql creates the objects

USE ROLE ACCOUNTADMIN;

-- Grant warehouse usage
GRANT USAGE, OPERATE ON WAREHOUSE $DEMO_WAREHOUSE TO ROLE $DEMO_ROLE;

-- Grant database/schema access
GRANT USAGE ON DATABASE SNOWFLAKE_EXAMPLE TO ROLE $DEMO_ROLE;
GRANT USAGE ON SCHEMA SNOWFLAKE_EXAMPLE.SFE_CORTEX_AGENT_CHAT TO ROLE $DEMO_ROLE;

-- Grant Cortex Agent usage
GRANT USAGE ON AGENT SNOWFLAKE_EXAMPLE.SFE_CORTEX_AGENT_CHAT.SFE_REACT_DEMO_AGENT 
    TO ROLE $DEMO_ROLE;

-- ============================================
-- STEP 4: Assign Public Key to Demo User
-- ============================================

-- Assign RSA public key to enable key-pair JWT authentication
ALTER USER $DEMO_USER SET RSA_PUBLIC_KEY='$PUBLIC_KEY';

-- Verify key assignment (should show RSA_PUBLIC_KEY_FP value)
DESC USER $DEMO_USER;

-- ============================================
-- Setup Complete!
-- ============================================
-- Demo user created: $DEMO_USER
-- 
-- Next steps:
-- 1. Update SNOWFLAKE_ACCOUNT in .env.server.local (backend)
-- 2. Update REACT_APP_SNOWFLAKE_ACCOUNT in .env.local (frontend)
-- 3. Run: npm install
-- 4. Run: npm run dev  (starts backend on :4000 and React on :3001)
-- 5. Open browser to http://localhost:3001
EOF

echo "✅ Generated complete SQL deployment script: $SQL_OUTPUT"
echo ""
echo "=========================================="
echo "🎉 Setup Complete!"
echo "=========================================="
echo ""
echo "Demo User Details:"
echo "  Username: $DEMO_USER"
echo "  Role: $DEMO_ROLE"
echo "  Auth: RSA Key-Pair (generated)"
echo ""
echo "Next Steps:"
echo ""
echo "1. Edit .env.server.local and update SNOWFLAKE_ACCOUNT (backend, holds private key)"
echo "   (Change 'your-account.us-east-1' to your actual account)"
echo "2. Edit .env.local and update REACT_APP_SNOWFLAKE_ACCOUNT (frontend, non-secret)"
echo ""
echo "3. Copy $SQL_OUTPUT into Snowsight and Run All"
echo "   (Run as ACCOUNTADMIN to create the demo user)"
echo ""
echo "4. Install dependencies and start app:"
echo "   npm install"
echo "   npm run dev   # backend :4000, frontend :3001"
echo ""
echo "5. Open http://localhost:3001 in your browser"
echo ""
echo "=========================================="
echo "🔒 Security Reminder"
echo "=========================================="
echo "✓ .env.local created (contains private key)"
echo "✓ rsa_key.pem created (private key file)"
echo "✓ rsa_key.pub created (public key file)"
echo ""
echo "⚠️  NEVER commit these files to version control!"
echo "⚠️  Store rsa_key.pem securely"
echo "⚠️  .gitignore already excludes these files"
echo ""
