@echo off
REM Cortex Agent Chat - Setup Automation (Windows)
REM Generates RSA key-pair and creates demo user for Snowsight deployment
REM Author: SE Community

REM Demo user configuration (no user input required)
set DEMO_USER=SFE_CORTEX_DEMO_USER
set DEMO_ROLE=SFE_CORTEX_DEMO_ROLE
set DEMO_WAREHOUSE=SFE_CORTEX_AGENT_WH

echo ==========================================
echo Cortex Agent Chat - Setup Automation
echo ==========================================
echo.
echo This script will:
echo   1. Generate RSA key-pair for authentication
echo   2. Create SQL to set up demo user: %DEMO_USER%
echo   3. Configure .env.local for the React app
echo.

REM Check for OpenSSL
where openssl >nul 2>nul
if %ERRORLEVEL% neq 0 (
    echo Error: openssl not found. Please install OpenSSL first.
    echo Download from: https://slproweb.com/products/Win32OpenSSL.html
    exit /b 1
)

echo Generating RSA key-pair...

REM Generate private key (2048-bit RSA in PKCS#1 format)
REM Using PKCS#1 for better jsrsasign compatibility
REM -traditional flag forces PKCS#1 format (OpenSSL 3.x defaults to PKCS#8)
openssl genrsa -traditional -out rsa_key.pem 2048 2>nul

REM Extract public key
openssl rsa -in rsa_key.pem -pubout -out rsa_key.pub 2>nul

echo Success: RSA key-pair generated!
echo    - Private key: rsa_key.pem
echo    - Public key: rsa_key.pub
echo.

REM Extract public key content (without BEGIN/END lines)
REM Windows doesn't have grep, so we'll use PowerShell
powershell -Command "$content = Get-Content rsa_key.pub | Where-Object { $_ -notmatch 'BEGIN|END' }; $content -join ''" > public_key_temp.txt
set /p PUBLIC_KEY=<public_key_temp.txt
del public_key_temp.txt

REM Create .env.local with escaped private key
echo # Cortex Agent Chat - Local Configuration > .env.local
echo # Generated: %DATE% >> .env.local
echo # WARNING: Never commit this file! Contains private key. >> .env.local
echo. >> .env.local
echo # Snowflake Connection >> .env.local
echo REACT_APP_SNOWFLAKE_ACCOUNT=your-account.us-east-1 >> .env.local
echo REACT_APP_SNOWFLAKE_USER=%DEMO_USER% >> .env.local
echo. >> .env.local
echo # Agent Configuration >> .env.local
echo REACT_APP_SNOWFLAKE_DATABASE=SNOWFLAKE_EXAMPLE >> .env.local
echo REACT_APP_SNOWFLAKE_SCHEMA=SFE_CORTEX_AGENT_CHAT >> .env.local
echo REACT_APP_CORTEX_AGENT_NAME=SFE_REACT_DEMO_AGENT >> .env.local
echo. >> .env.local
echo # RSA Private Key ^(generated: %DATE%^) >> .env.local

REM Use PowerShell to properly escape the private key
powershell -Command "$key = Get-Content rsa_key.pem -Raw; $escaped = $key -replace '`r`n', '\n'; $escaped = $escaped.TrimEnd(); Write-Host \"REACT_APP_SNOWFLAKE_PRIVATE_KEY=`\"$escaped`\"\"" >> .env.local

echo Success: Created .env.local configuration file
echo.

REM Generate complete SQL script
set SQL_OUTPUT=deploy_with_key.sql

echo -- Cortex Agent Chat - Complete Setup > %SQL_OUTPUT%
echo -- Generated by tools/01_setup.bat >> %SQL_OUTPUT%
echo -- Creates demo user + deploys agent + assigns public key >> %SQL_OUTPUT%
echo -- >> %SQL_OUTPUT%
echo -- INSTRUCTIONS: >> %SQL_OUTPUT%
echo -- 1. Copy this ENTIRE script >> %SQL_OUTPUT%
echo -- 2. Paste into Snowsight ^(as ACCOUNTADMIN or role with CREATE USER privilege^) >> %SQL_OUTPUT%
echo -- 3. Click "Run All" >> %SQL_OUTPUT%
echo -- 4. Return to terminal and run: npm install ^&^& npm start >> %SQL_OUTPUT%
echo. >> %SQL_OUTPUT%
echo -- ============================================ >> %SQL_OUTPUT%
echo -- STEP 1: Create Demo User and Role >> %SQL_OUTPUT%
echo -- ============================================ >> %SQL_OUTPUT%
echo. >> %SQL_OUTPUT%
echo USE ROLE ACCOUNTADMIN; >> %SQL_OUTPUT%
echo. >> %SQL_OUTPUT%
echo -- Create warehouse for this tool >> %SQL_OUTPUT%
echo CREATE WAREHOUSE IF NOT EXISTS %DEMO_WAREHOUSE% >> %SQL_OUTPUT%
echo     WITH WAREHOUSE_SIZE = 'XSMALL' >> %SQL_OUTPUT%
echo     AUTO_SUSPEND = 60 >> %SQL_OUTPUT%
echo     AUTO_RESUME = TRUE >> %SQL_OUTPUT%
echo     INITIALLY_SUSPENDED = TRUE >> %SQL_OUTPUT%
echo     COMMENT = 'DEMO: Warehouse for Cortex Agent Chat demo'; >> %SQL_OUTPUT%
echo. >> %SQL_OUTPUT%
echo -- Create demo role if not exists >> %SQL_OUTPUT%
echo CREATE ROLE IF NOT EXISTS %DEMO_ROLE% >> %SQL_OUTPUT%
echo     COMMENT = 'DEMO: Role for Cortex Agent Chat demo user'; >> %SQL_OUTPUT%
echo. >> %SQL_OUTPUT%
echo -- Create demo user with key-pair authentication ONLY ^(no password^) >> %SQL_OUTPUT%
echo CREATE USER IF NOT EXISTS %DEMO_USER% >> %SQL_OUTPUT%
echo     DEFAULT_ROLE = %DEMO_ROLE% >> %SQL_OUTPUT%
echo     DEFAULT_WAREHOUSE = %DEMO_WAREHOUSE% >> %SQL_OUTPUT%
echo     TYPE = SERVICE >> %SQL_OUTPUT%
echo     COMMENT = 'DEMO: Demo user for Cortex Agent Chat ^(key-pair auth only^)'; >> %SQL_OUTPUT%
echo. >> %SQL_OUTPUT%
echo -- Assign role to user >> %SQL_OUTPUT%
echo GRANT ROLE %DEMO_ROLE% TO USER %DEMO_USER%; >> %SQL_OUTPUT%
echo. >> %SQL_OUTPUT%
echo -- ============================================ >> %SQL_OUTPUT%
echo -- STEP 2: Deploy Cortex Agent >> %SQL_OUTPUT%
echo -- ============================================ >> %SQL_OUTPUT%
echo -- This creates the schema, agent, and warehouse >> %SQL_OUTPUT%
echo -- Grants come AFTER these objects exist >> %SQL_OUTPUT%
echo. >> %SQL_OUTPUT%

REM Append original deploy.sql
type deploy.sql >> %SQL_OUTPUT%

REM Add grants and public key assignment AFTER objects exist
echo. >> %SQL_OUTPUT%
echo -- ============================================ >> %SQL_OUTPUT%
echo -- STEP 3: Grant Permissions to Demo Role >> %SQL_OUTPUT%
echo -- ============================================ >> %SQL_OUTPUT%
echo -- These grants come AFTER deploy.sql creates the objects >> %SQL_OUTPUT%
echo. >> %SQL_OUTPUT%
echo USE ROLE ACCOUNTADMIN; >> %SQL_OUTPUT%
echo. >> %SQL_OUTPUT%
echo -- Grant warehouse usage >> %SQL_OUTPUT%
echo GRANT USAGE, OPERATE ON WAREHOUSE %DEMO_WAREHOUSE% TO ROLE %DEMO_ROLE%; >> %SQL_OUTPUT%
echo. >> %SQL_OUTPUT%
echo -- Grant database/schema access >> %SQL_OUTPUT%
echo GRANT USAGE ON DATABASE SNOWFLAKE_EXAMPLE TO ROLE %DEMO_ROLE%; >> %SQL_OUTPUT%
echo GRANT USAGE ON SCHEMA SNOWFLAKE_EXAMPLE.SFE_CORTEX_AGENT_CHAT TO ROLE %DEMO_ROLE%; >> %SQL_OUTPUT%
echo. >> %SQL_OUTPUT%
echo -- Grant Cortex Agent usage >> %SQL_OUTPUT%
echo GRANT USAGE ON AGENT SNOWFLAKE_EXAMPLE.SFE_CORTEX_AGENT_CHAT.SFE_REACT_DEMO_AGENT >> %SQL_OUTPUT%
echo     TO ROLE %DEMO_ROLE%; >> %SQL_OUTPUT%
echo. >> %SQL_OUTPUT%
echo -- ============================================ >> %SQL_OUTPUT%
echo -- STEP 4: Assign Public Key to Demo User >> %SQL_OUTPUT%
echo -- ============================================ >> %SQL_OUTPUT%
echo. >> %SQL_OUTPUT%
echo -- Assign RSA public key to enable key-pair JWT authentication >> %SQL_OUTPUT%
echo ALTER USER %DEMO_USER% SET RSA_PUBLIC_KEY='%PUBLIC_KEY%'; >> %SQL_OUTPUT%
echo. >> %SQL_OUTPUT%
echo -- Verify key assignment ^(should show RSA_PUBLIC_KEY_FP value^) >> %SQL_OUTPUT%
echo DESC USER %DEMO_USER%; >> %SQL_OUTPUT%
echo. >> %SQL_OUTPUT%
echo -- ============================================ >> %SQL_OUTPUT%
echo -- Setup Complete! >> %SQL_OUTPUT%
echo -- ============================================ >> %SQL_OUTPUT%
echo -- Demo user created: %DEMO_USER% >> %SQL_OUTPUT%
echo -- >> %SQL_OUTPUT%
echo -- Next steps: >> %SQL_OUTPUT%
echo -- 1. Update REACT_APP_SNOWFLAKE_ACCOUNT in .env.local >> %SQL_OUTPUT%
echo -- 2. Run: npm install >> %SQL_OUTPUT%
echo -- 3. Run: npm start >> %SQL_OUTPUT%
echo -- 4. Open browser to http://localhost:3001 >> %SQL_OUTPUT%

echo Success: Generated complete SQL deployment script: %SQL_OUTPUT%
echo.
echo ==========================================
echo Setup Complete!
echo ==========================================
echo.
echo Demo User Details:
echo   Username: %DEMO_USER%
echo   Role: %DEMO_ROLE%
echo   Auth: RSA Key-Pair ^(generated^)
echo.
echo Next Steps:
echo.
echo 1. Edit .env.local and update REACT_APP_SNOWFLAKE_ACCOUNT
echo    ^(Change 'your-account.us-east-1' to your actual account^)
echo.
echo 2. Copy %SQL_OUTPUT% into Snowsight and Run All
echo    ^(Run as ACCOUNTADMIN to create the demo user^)
echo.
echo 3. Install dependencies and start app:
echo    npm install
echo    npm start
echo.
echo 4. Open http://localhost:3001 in your browser
echo.
echo ==========================================
echo Security Reminder
echo ==========================================
echo - .env.local created ^(contains private key^)
echo - rsa_key.pem created ^(private key file^)
echo - rsa_key.pub created ^(public key file^)
echo.
echo WARNING: NEVER commit these files to version control!
echo WARNING: Store rsa_key.pem securely
echo .gitignore already excludes these files
echo.

pause
